name: build and upload

on:
  push:
    tags: 'oj_*'
      
env:
  USE_SENTRY: 0
  CXX: g++-4.8
      
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 16
    - name: Install Dependencies
      run: npm install
    - name: Build DLL
      run: npm run build:dll
    - name: Build       
      run: npm run build
    - name: Prep
      run: find dist/ -type f -name "*.map" -delete
    - name: Zip Dist
      run: zip -r dist.zip dist
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip

