name: build and upload

on:
  push:
    branches:
      - 'master'
      
env:
  USE_SENTRY: 0
  CXX: g++-4.8
      
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 16
    - name: Install Dependencies
      run: npm install
    - name: Build DLL
      run: npm run build:dll
    - name: Build       
      run: npm run build
    - name: Prep
      run: find dist/ -type f -name "*.map" -delete
    - name: Zip Dist
      run: zip -r dist.zip dist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dist.zip
        path: dist.zip

